### ISSUE TITLE
Module not found: Can't resolve './beaconUtils'

### ISSUE THREAD

**Issue by angelfeliz** [Constructor-io/constructorio-ui-autocomplete#143] opened 2024-05-21 21:23 UTC
Hello:

Version :   `"@constructor-io/constructorio-ui-autocomplete": "^1.22.0"`

Getting the following error:

> error ./node_modules/@constructor-io/constructorio-ui-autocomplete/lib/mjs/utils.js:3:0
> Module not found: Can't resolve './beaconUtils'

How are you importing the library?
`import { CioAutocomplete } from '@constructor-io/constructorio-ui-autocomplete'`

What version of Next are you on?
_NextJS: 13.4.4_

What version of Node are you on?
_Nodjs:  20.11.0_

**Comment by esezen** [comment] 2024-05-21 23:01
Hello @angelfeliz ,

Thanks for reporting this issue in great detail with all of the additional information. We found the root cause of the issue and released a fix with version [v1.22.1](https://www.npmjs.com/package/@constructor-io/constructorio-ui-autocomplete/v/1.22.1).
Please install the latest version of the library and let us know if you run into any issues.

Thanks again for reporting this issue.

**Comment by esezen** [comment] 2024-05-23 17:27
@angelfeliz I am going to close this issue as we believe it to be resolved and I see a thumbs up emoji response from you. Please feel free to comment on this issue if you are still having problems and I would be happy to re-open it. Thanks again for reporting this issue - we appreciate your help in diagnosing and for your contribution to the repository.

**Closed by esezen** 2024-05-23 17:27 UTC
